import { z } from 'zod';

const apexDateTimeSerializationPattern =
  /^\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\d|3[01])T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d\.\d{3}Z$/;

// Apex's JSON.serialize(DateTime) always produces exactly three fractional
// digits (e.g. "2026-09-21T23:36:05.153Z") with real, arbitrary milliseconds.
// This differs from apexCompatibleUtcDateTimeSchema (event-grid.ts), which is
// scoped to the simulator's OWN outgoing Event Grid envelope generation and
// only accepts ".000" or no fraction — inadequate for an INCOMING timestamp
// generated by real Apex code.
const pacCreditoDataCriacaoSchema = z
  .string()
  .regex(
    apexDateTimeSerializationPattern,
    'Expected Apex DateTime.serialize format (UTC, exactly 3 fractional digits, ending in Z)',
  )
  .refine(
    (value) => !Number.isNaN(new Date(value).getTime()),
    'Invalid UTC datetime',
  );

export const pacCreditoRequestSchema = z
  .object({
    IdSalesforcePac: z.string().min(1),
    IdPac: z.string().min(1),
    IdJornada: z.string().min(1).nullable().optional(),
    DataCriacao: pacCreditoDataCriacaoSchema,
  })
  // .passthrough() (not .strict()): mrv-staging's real EnvioPACCreditoQueue
  // traffic was observed (Fase 7, docs/staging-logs-analysis.md) sending an
  // extra "CodigoPAC" field that the version deployed to mrv-devDan does not
  // have — evidence of real version drift between environments. Rejecting
  // unknown fields would make this endpoint fragile to any future field the
  // real Apex adds; only the 4 fields we actually rely on are validated.
  .passthrough();

export type PacCreditoRequest = z.infer<typeof pacCreditoRequestSchema>;
